repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-merge-conflict
  - id: mixed-line-ending
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: detect-private-key
  - id: destroyed-symlinks
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-ast
  - id: double-quote-string-fixer
  - id: requirements-txt-fixer
  - id: check-xml
  - id: check-yaml
  rev: v5.0.0
- repo: https://github.com/codespell-project/codespell
  hooks:
  - id: codespell
    args:
    - --write-changes
  rev: v2.4.1
- repo: https://github.com/psf/black
  hooks:
  - id: black
  rev: 25.1.0
- repo: https://github.com/pycqa/isort
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
  rev: 6.0.1
- repo: https://github.com/PyCQA/flake8
  hooks:
  - id: flake8
  rev: 7.2.0
- repo: local
  hooks:
  - id: pytest-check
    name: pytest-check
    entry: pytest
    language: system
    pass_filenames: false
    always_run: true
ci:
  autoupdate_schedule: quarterly