/static_transform_publisher:
  ros__parameters:
    child_frame_id: /dummy_link
    frame_id: /map
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf_static:
        publisher:
          depth: 1
          history: keep_last
          reliability: reliable
    rotation:
      w: 1.0
      x: 0.0
      y: 0.0
      z: 0.0
    translation:
      x: 1.0
      y: 0.0
      z: 0.0
    use_sim_time: false
