controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

    position_controller:
      type: position_controllers/JointGroupPositionController

position_controller:
  ros__parameters:
    joints:
      - front_right_leg1_corpus_joint
      - front_right_leg1_leg2_joint
      - front_left_leg1_corpus_joint  
      - front_left_leg1_leg2_joint
      - back_right_leg1_corpus_joint
      - back_right_leg1_leg2_joint
      - back_left_leg1_corpus_joint
      - back_left_leg1_leg2_joint
    interface_name: position