/sensors/imu_filter:
  ros__parameters:
    constant_dt: 0.0
    declination: 0.0
    fixed_frame: odom
    gain: 0.1
    mag_bias_x: 0.0
    mag_bias_y: 0.0
    mag_bias_z: 0.0
    orientation_stddev: 0.01
    angular_velocity_stddev: 0.02
    publish_debug_topics: false
    publish_tf: false
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    remove_gravity_vector: false
    reverse_tf: false
    stateless: false
    use_mag: false
    use_sim_time: true
    world_frame: enu
    yaw_offset: 0.0
    zeta: 0.03
    wait_for_transform: 0.2
    transform_timeout: 0.05
