services:
  app:
    image: $DOCKER_IMAGE
    container_name: ros_gazebo_robot
    command: $WORKSPACE_ROOT/ros_run.sh
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
    volumes:
      - $PROJECT_DIR/ros_robotics:$CONTAINER_WORKDIR/ros_robotics
      - $PROJECT_DIR/.env:$CONTAINER_WORKDIR/.env
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    env_file:
      - ../../.env
    ports:
      - $TENSORBOARD_PORT:$TENSORBOARD_PORT
    restart: unless-stopped
    stop_signal: SIGINT
